var addClass = function (element, className) {
    var classNames = element.className.split(/\s+/);
    if (classNames.indexOf(className) == -1) {
        classNames.push(className);
    }
    element.className = classNames.join(' ')
}

var arr = [
    { type: 'wait', time: 2000 },
    { type: 'text', text: '何以与君识/' },
    { type: 'wait', time: 1000 },
    { type: 'text', text: '无言泪千行' },
    // {type: 'wait',time: 500},'<br>',
    // {type: 'wait',time: 500},'<br>',
    // {type: 'wait',time: 500},
    // {type: 'text',text: '测试的数据测试的数据,'},
    // {type: 'wait',time: 700},
    // {type: 'text',text: '测试的数据测试的数据'},
    // {type: 'wait',time: 1500},
    // {type: 'text',text: '测试的数据测试的数据'},
    // {type: 'wait',time: 700},'<br>',
    // {type: 'wait',time: 700},'<br>',
    // {type: 'wait',time: 500},
    // {type: 'text',text: '你测试的数据测试的数据说过，'},
    // {type: 'wait',time: 700},
    // {type: 'text',text: '测试的数据测试的数据'},
    // {type: 'wait',time: 600},'<br>',
    // {type: 'wait',time: 600},
    // {type: 'text',text: '测试的数据测试的数据'},
    // {type: 'wait',time: 500},
    // {type: 'text',text: '测试的数据测试的数据'},
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500},
    // {type: 'text',text: '测试的数据测试的数据'},
    // {type: 'wait',time: 700},
    // {type: 'text',text: '测试的数据测试的数据',},
    // {type: 'wait',time: 700},'<br>',
    // {type: 'wait',time: 500},
    // {type: 'text',text: '测试的数据测试的数据'},
    // {type: 'wait',time: 700},'<br>',
    // {type: 'wait',time: 500},
    // {type: 'text',text: '测试的数据测试的数据,'},
    // {type: 'wait',time: 700},
    // {type: 'text',text: ''},
    // {type: 'wait',time: 700},'<br>',
    // {type: 'wait',time: 500},
    // {type: 'text',text: '测试的数据测试的数据'},
    // {type: 'wait',time: 700},'<br>',
    // {type: 'wait',time: 500},
    // {type: 'text',text: '可能是忍的太久，'},
    // {type: 'wait',time: 700},
    // {type: 'text',text: '似乎每次找你你都会生气啊。'},
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500},
    // {type: 'text',text: '知道吗，我最喜欢过节了，'},
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500},
    // {type: 'text',text: '只有那时可以毫无顾虑的给你发句“节日快乐”。'},
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500},
    // {type: 'text',text: '爱你呀范，ai ni ya fan,anyfan。'},
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500},
    // {type: 'text',text: 'anyfan',time: 100},
    // {type: 'text',text: '，不知不觉成为我最优选的名字。'},
    // {type: 'wait',time: 700},
    // {type: 'wait',time: 500},
    // {type: 'br'},
    // {type: 'text',text: '知道你有男朋友的时候，'},
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500}, 
    // {type: 'text',text: '惶恐,',}, 
    // {type: 'wait',time: 600}, 
    // {type: 'text',text: '抑郁,',}, 
    // {type: 'wait',time: 600}, 
    // {type: 'text',text: '不安,',},
    // {type: 'wait',time: 600},
    // {type: 'text',text: '突然失去了整个世界。'}, 
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500},
    // {type: 'text',text: '想和你说好多话，'}, 
    // {type: 'wait',time: 500}, 
    // {type: 'text',text: '打了很多字，'}, 
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500}, 
    // {type: 'text',text: '最后还是删掉了，'}, 
    // {type: 'wait',time: 700},
    // {type: 'text',text: '终究 '}, 
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500}, 
    // {type: 'text',text: '放弃吗？'},
    // {type: 'wait',time: 600}, 
    // {type: 'text',text: '真的很喜欢你啊。'}, 
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500}, 
    // {type: 'text',text: '哈哈，这么多字，可能你根本不会看吧。'}, 
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500}, 
    // {type: 'text',text: '或许，'}, 
    // {type: 'wait',time: 700}, 
    // {type: 'text',text: '你从未知道过这个页面。'},
    // {type: 'wait',time: 700},'<br>', 
    // {type: 'wait',time: 500}, 
    // {type: 'text',text: '又或许'}, 
    // {type: 'wait',time: 500}, 
    // {type: 'text',text: '你就从未喜欢过我吧，'}, 
    // {type: 'wait',time: 1000}, 
    // {type: 'text',text: '嗯？'}, 
    // {type: 'wait',time: 3000}, 
    // {type: 'delete',num: 2}, 
    // {type: 'text',text: '嗯！'},
    // {type: 'wait',time: 3000},'<br>', 
    // {type: 'wait',time: 500}, 
    // {type: 'text',text: '又或许，'}, 
    // {type: 'wait',time: 2000}, 
    // {type: 'text',text: '根本从未记得过这么一个人吧。'}, 
    // {type: 'wait',time: 3000}, 
    // {type: 'delete',num: 3}, 
    // {type: 'delete',num: 9,time: 150}, 
    // {type: 'delete',num: 9,time: 100}, 
    // {type: 'delete',num: 9,time: 50}, 
    // {type: 'delete',num: 98,time: 25},
    // {type: 'wait',time: 2000}, 
    // {type: 'text',text: '祝你们幸福',time: 630}, 
    // {type: 'text',text: '！！！'}, 
    // {type: 'wait',time: 1000},"<br>", 
    // {type: 'wait',time: 500}, 
    // {type: 'text',text: '至少 '}, 
    // {type: 'wait',time: 1000}, 
    // {type: 'text',text: '对你 '}, 
    // {type: 'wait',time: 1000}, 
    // {type: 'text',text: '也曾 '}, 
    // {type: 'wait',time: 1000}, 
    // {type: 'text',text: '疯狂'}, 
    // {type: 'wait',time: 600}, 
    // {type: 'text',text: '。'}, 
    // {type: 'wait',time: 3000},"<br>",
    // {type: 'wait',time: 1000},"<br>",
    // {type: 'wait',time: 500}, 
    // {type: 'text',text: 'FROM/'}, 
    // {type: 'wait',time: 2000}, 
    // {type: 'text',text: '一个爱你的路人'}, 
    // {type: 'wait',time: 3000}
]

// var autoType = new AutoType("#content", arr);
// autoType.once("end", function () {
//     addClass(content, 'end'), document.querySelector('#clock-box').classList.add('clock-show')
// })

// setInterval(timeElapse, 1000);